### ISSUE TITLE
PiPU on RetroUSB AVS

### ISSUE THREAD

**Issue by IgorTregubov** [rasteri/PiPU#1]
Hello.
Thank you very much for sharing. PiPU is great.

This is how doom runs on RetroUSB AVS fpga nes clone 
(hdmi in 720p, video attached).
![PiPU__AVS](https://user-images.githubusercontent.com/56859749/68091709-c32e2000-fe8b-11e9-8c7c-283e313defee.gif)

Please, help. Is this an expected behavior,
or bad assembly and can be fixed?

**Comment by rasteri** [comment]
Can you test it on a stock NES? It could be assembly issues but I'd want to rule out the AVS first.

**Comment by IgorTregubov** [comment]
Unfortunately, not right now.
I'll buy an NES console and, probably, other FX2LP and reply about results.

**Comment by IgorTregubov** [comment]
My FX2LP was different than the one used in tutorial video.
I changed it and it works much better.
With the stock NES - much, much better. 

![fl](https://user-images.githubusercontent.com/56859749/77370383-6ca57d80-6d69-11ea-888a-f76c339bb89e.jpg)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/56859749/77370418-7d55f380-6d69-11ea-833e-5240ec37afa6.gif)

Thanks again.
